#!/usr/bin/env bash
#
# Writes the admin panel's config.php from environment variables.
#
# This file used to be placed by hand and never deployed, which made it a
# reliable marker for "the real panel is here". That was worth something while
# the panel's location was unknown. It stopped being worth the cost once the
# only remaining task was copying one 577-byte file between two directories
# that look identical in two different file browsers -- which took most of a
# day and never succeeded.
#
# The credentials live in GitHub Actions secrets and are written here at
# deploy time. Nothing sensitive is committed, and nothing is printed: the
# values reach the file through the environment and are never echoed, so a
# public build log cannot leak them.
#
# Usage: DB_HOST=... DB_NAME=... DB_USER=... DB_PASSWORD=... \
#          write-admin-config.sh <output-path>

set -uo pipefail

out="${1:?usage: write-admin-config.sh <output-path>}"

: "${DB_NAME:?DB_NAME is not set}"
: "${DB_USER:?DB_USER is not set}"
: "${DB_PASSWORD:?DB_PASSWORD is not set}"

host="${DB_HOST:-localhost}"
charset="${DB_CHARSET:-utf8mb4}"
storage="${STORAGE_PATH:-__DIR__ . '/../nitesha-storage'}"
idle="${SESSION_IDLE_MINUTES:-120}"
https_only="${HTTPS_ONLY:-true}"

# PHP single-quoted strings take exactly two escapes: a backslash and a single
# quote. Anything else is literal. Without this a password containing an
# apostrophe writes a config.php that is a PHP syntax error -- the panel would
# answer every request with a blank page, and the cause would not be visible
# from anywhere.
php_str() {
  printf '%s' "$1" | sed "s/\\\\/\\\\\\\\/g; s/'/\\\\'/g"
}

# The origin list is only consulted for cross-origin requests. The site and the
# panel now share a host, so this is belt and braces -- but it costs nothing and
# keeps the panel usable if the two are ever split across hosts again.
origins="${PUBLIC_SITE_ORIGIN:-https://niteshacars.in,https://www.niteshacars.in}"
origin_lines=""
IFS=',' read -ra parts <<< "$origins"
for origin in "${parts[@]}"; do
  origin="$(printf '%s' "$origin" | tr -d '[:space:]')"
  [ -n "$origin" ] || continue
  origin_lines="${origin_lines}        '$(php_str "$origin")',"$'\n'
done

umask 077
cat > "$out" <<PHP
<?php
// Generated by .github/scripts/write-admin-config.sh during deployment.
// Do not edit on the server: the next deploy overwrites it. Change the values
// in GitHub -> Settings -> Secrets and variables -> Actions instead.

return [
    'db' => [
        'host'     => '$(php_str "$host")',
        'name'     => '$(php_str "$DB_NAME")',
        'user'     => '$(php_str "$DB_USER")',
        'password' => '$(php_str "$DB_PASSWORD")',
        'charset'  => '$(php_str "$charset")',
    ],

    'storage_path' => ${storage},

    'public_site_origin' => [
${origin_lines}    ],

    'https_only' => ${https_only},

    'session_idle_minutes' => ${idle},
];
PHP

# Reports shape, never contents. A build log on a public repository is public.
echo "write-admin-config: wrote $(wc -c < "$out") bytes to $out"
